name: rockers_app
description: Rockers Rock Music App
publish_to: "none"
version: 2.2.0+8

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.4
  firebase_core: ^3.12.0
  firebase_remote_config: ^5.4.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.5
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  intl: ^0.20.2
  package_info_plus: ^8.2.1
  pub_semver: ^2.2.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  youtube_explode_dart: ^2.3.10
  youtube_player_iframe: ^5.2.1

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/rockers-icon-app.png"
  adaptive_icon_background: "#1D1D1D"
  adaptive_icon_foreground: "assets/images/rockers-icon-app.png"
  min_sdk_android: 21

flutter_native_splash:
  image: "assets/images/rockers-icon-app.png"
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Kollektif
      fonts:
        - asset: assets/fonts/Kollektif/Kollektif-Bold.ttf
        - asset: assets/fonts/Kollektif/Kollektif-BoldItalic.ttf
        - asset: assets/fonts/Kollektif/Kollektif-Italic.ttf
        - asset: assets/fonts/Kollektif/Kollektif.ttf
    - family: ManoNegra
      fonts:
        - asset: assets/fonts/ManoNegra/ManoNegra-Bold.ttf
        - asset: assets/fonts/ManoNegra/ManoNegra-Regular.ttf
