name: rockers_app
description: Rockers Rock Music App
publish_to: "none"
version: 2.1.1+6

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cloud_firestore: ^5.3.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1
  google_sign_in: ^6.1.3
  intl: ^0.18.1
  package_info_plus: ^4.0.2
  share_plus: ^7.0.2
  shared_preferences: ^2.1.1
  youtube_explode_dart: ^1.12.4
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/rockers-icon-app.png"
  adaptive_icon_background: "#1D1D1D"
  adaptive_icon_foreground: "assets/images/rockers-icon-app.png"
  min_sdk_android: 21

flutter_native_splash:
  image: "assets/images/rockers-icon-app.png"
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Kollektif
      fonts:
        - asset: assets/fonts/Kollektif/Kollektif-Bold.ttf
        - asset: assets/fonts/Kollektif/Kollektif-BoldItalic.ttf
        - asset: assets/fonts/Kollektif/Kollektif-Italic.ttf
        - asset: assets/fonts/Kollektif/Kollektif.ttf
    - family: ManoNegra
      fonts:
        - asset: assets/fonts/ManoNegra/ManoNegra-Bold.ttf
        - asset: assets/fonts/ManoNegra/ManoNegra-Regular.ttf
