// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:rockers_app/config/config.dart' show Environment;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static final Environment _environment = Environment.prod();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: _environment.firebaseWebApiKey,
    appId: _environment.firebaseAppId,
    messagingSenderId: '497715268668',
    projectId: 'rockers-db',
    authDomain: 'rockers-db.firebaseapp.com',
    databaseURL: 'https://rockers-db.firebaseio.com',
    storageBucket: 'rockers-db.appspot.com',
    measurementId: 'G-9TK284K1F0',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: _environment.firebaseAndroidApiKey,
    appId: _environment.firebaseAppId,
    messagingSenderId: '497715268668',
    projectId: 'rockers-db',
    databaseURL: 'https://rockers-db.firebaseio.com',
    storageBucket: 'rockers-db.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: _environment.firebaseIosApiKey,
    appId: _environment.firebaseAppId,
    messagingSenderId: '497715268668',
    projectId: 'rockers-db',
    databaseURL: 'https://rockers-db.firebaseio.com',
    storageBucket: 'rockers-db.appspot.com',
    androidClientId: _environment.firebaseAndroidClientId,
    iosClientId: _environment.firebaseIosClientId,
    iosBundleId: 'com.bl4kcrow.rockersApp',
  );
}
